In [1]:
dataset_drive_url="https://drive.google.com/file/d/1VTY0ff69sMqCJ_rrEgxVIteWV3Hgg6MI/view?usp=sharing"

In [2]:
import re

def drive_to_direct_url(link: str) -> str:
    """
    Convert Google Drive share link to direct download URL.
    Works for multiple link formats.
    """
    patterns = [
        r'/file/d/([a-zA-Z0-9_-]+)',
        r'id=([a-zA-Z0-9_-]+)',
        r'/open\?id=([a-zA-Z0-9_-]+)'
    ]
    
    file_id = None
    
    for pattern in patterns:
        match = re.search(pattern, link)
        if match:
            file_id = match.group(1)
            break
    
    if not file_id:
        raise ValueError("Invalid Google Drive link")
    
    return f"https://drive.google.com/uc?id={file_id}"

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
path = drive_to_direct_url(dataset_drive_url)

path

'https://drive.google.com/uc?id=1VTY0ff69sMqCJ_rrEgxVIteWV3Hgg6MI'

In [5]:
df=pd.read_csv(path)

In [6]:
df.head()

,No. of Pregnancy,Age,BMI,BP(Systolic),BP(Diastolic),DiabetesPedigreeFunction,Insulin,Skin Thickness(mm),Type-2 Diabetic,Glucose
0,3,50,22.263762,140,90.0,0,0,317.50,1,146.0
1,1,40,24.111159,110,80.0,2,0,317.50,0,61.0
2,0,21,17.183204,120,80.0,0,0,259.08,1,97.0
3,2,30,21.244332,130,85.0,0,0,322.58,1,178.0
4,2,35,22.819490,110,75.0,0,0,335.28,1,167.0

In [7]:
df.shape

(1065, 10)

In [8]:
df.columns.tolist()

['No. of Pregnancy',
 'Age',
 'BMI',
 'BP(Systolic)',
 'BP(Diastolic)',
 'DiabetesPedigreeFunction',
 'Insulin',
 'Skin Thickness(mm)',
 'Type-2 Diabetic',
 'Glucose']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   No. of Pregnancy          1065 non-null   int64
 1   Age                       1065 non-null   int64
 2   BMI                       1065 non-null   float64
 3   BP(Systolic)              1065 non-null   int64
 4   BP(Diastolic)             1061 non-null   float64
 5   DiabetesPedigreeFunction  1065 non-null   int64
 6   Insulin                   1065 non-null   int64
 7   Skin Thickness(mm)        1058 non-null   float64
 8   Type-2 Diabetic           1065 non-null   int64
 9   Glucose                   1065 non-null   float64
dtypes: float64(4), int64(6)
memory usage: 83.3 KB

In [10]:
df.isnull().sum()

No. of Pregnancy            0
Age                         0
BMI                         0
BP(Systolic)                0
BP(Diastolic)               4
DiabetesPedigreeFunction    0
Insulin                     0
Skin Thickness(mm)          7
Type-2 Diabetic             0
Glucose                     0
dtype: int64

In [11]:
df.describe(include="all").transpose()

,count,mean,std,min,25%,50%,75%,max
No. of Pregnancy,1065.0,3.114554,1.878355,0.000000,2.000000,3.000000,4.000000,12.000000
Age,1065.0,44.467606,12.695950,21.000000,35.000000,44.000000,53.000000,86.000000
BMI,1065.0,25.246733,3.800444,17.183204,22.650587,24.603224,27.492665,37.442807
BP(Systolic),1065.0,119.350235,14.289513,80.000000,110.000000,120.000000,130.000000,180.000000
BP(Diastolic),1061.0,79.829406,10.770160,30.000000,70.000000,80.000000,80.000000,120.000000
DiabetesPedigreeFunction,1065.0,1.487324,1.560822,0.000000,0.000000,1.000000,2.000000,8.000000
Insulin,1065.0,5.406573,8.879252,0.000000,0.000000,0.000000,12.000000,44.000000
Skin Thickness(mm),1058.0,307.242769,35.366131,29.210000,287.020000,304.800000,330.200000,406.400000
Type-2 Diabetic,1065.0,0.788732,0.408400,0.000000,1.000000,1.000000,1.000000,1.000000
Glucose,1065.0,138.448920,64.832444,50.000000,80.000000,129.000000,178.000000,450.000000

In [12]:
df.nunique()

No. of Pregnancy             13
Age                          55
BMI                         185
BP(Systolic)                 15
BP(Diastolic)                14
DiabetesPedigreeFunction      8
Insulin                      21
Skin Thickness(mm)           40
Type-2 Diabetic               2
Glucose                     146
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(569)

In [14]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(df[col].value_counts())

In [15]:
%pip install fg-data-profiling

Requirement already satisfied: fg-data-profiling in c:\users\habib\anaconda3\lib\site-packages (4.19.1)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (2.10.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\habib\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (2.1.3)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=4 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.2 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (1.9.5)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\habib\anaconda3\lib\site-packages (from fg-data-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\habib\anaconda3\lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\habib\anaconda3\lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\habib\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\habib\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\habib\anaconda3\lib\site-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\habib\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\habib\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\habib\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\habib\anaconda3\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\habib\anaconda3\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\habib\anaconda3\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\habib\anaconda3\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\habib\anaconda3\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\habib\anaconda3\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\habib\anaconda3\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2025.11.12)
Requirement already satisfied: patsy>=0.5.6 in c:\users\habib\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\habib\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->fg-data-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\habib\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (24.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\habib\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.4.2)
Requirement already satisfied: puremagic in c:\users\habib\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (1.30)
Requirement already satisfied: six>=1.5 in c:\users\habib\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import data_profiling
from data_profiling import ProfileReport

profile = ProfileReport(df, title="Profiling Report")

In [18]:
profile.to_notebook_iframe()

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [20]:
from pathlib import Path

if not Path("profile.html").exists():
    profile.to_file("profile.html")